services:
  asignaturas-servicio:
    build:
      context: ./asignaturas-servicio
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - eureka-server
    networks:
      - microservices-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/microservices_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    restart: always

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: microservices_db
    ports:
      - "3306:3306"  # Considera eliminar esta línea si no necesitas acceso externo
    networks:
      - microservices-network
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  eureka-server:
    build:
      context: ./eureka-server  # Ruta donde se encuentra el Dockerfile de Eureka Server
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    restart: always

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-data:
