server:
  port: 8081

spring:
  application:
    name: usuarios-servicio
  datasource:
    url: jdbc:mysql://localhost:3306/usuarios_db
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
